### ISSUE TITLE
Move to spacepy group owner?

### ISSUE THREAD

**Issue by balarsen** [drsteve/LANLGeoMag#10]
This has been a touch quiet. Should we move it to spacepy org with the goal of replacing the current spacepy Fortran?

**Comment by drsteve** [comment]
I would still love to get LANLGeoMag into SpacePy as a possible backend for the field tracing, etc., but LANLGeoMag is referenced in papers with the URL pointing here. Moving it to the SpacePy group isn't even really necessary when we finally have SpacePy integration.

Until there's a clear path to a Windows build for LGM, it's going to remain a long way out from being used by SpacePy. Another issue is that currently LANLGeoMag's Python wrapper is (to my knowledge) Python 2 only. Those should probably be filed as issues here.

If we wanted to up the visibility of the project we can file an issue over at SpacePy and make a project board for steps towards LANLGeoMag integration. There's a lot of work required on both sides though.
