### ISSUE TITLE
ctypesgen failure to generate wrapper.

### ISSUE THREAD

**Issue by jtniehof** [drsteve/LANLGeoMag#12]
Ubuntu 18.04.1, Python 2.7.15rc1, lgm 7a095d07ff8f3709620a7208dfef40bd978ee20e, using the ctypes in the repo. ctypesgen log is attached.

[ctypesgen.log](https://github.com/drsteve/LANLGeoMag/files/2818311/ctypesgen.log)

This is annoyingly deep. Obviously the literal is invalid for base 8, but that doesn't help with root cause. This works on Ubuntu 16.04.

**Comment by jtniehof** [comment]
Same problem dropping-in the latest ctypesgen from https://github.com/davidjamesca/ctypesgen

**Comment by jtniehof** [comment]
I grabbed Lgm_Wrap.py from another machine where it worked, touched Lgm_Wrap_gen.py so it looked up-to-date, and then installed successfully and was able to run at least some stuff.

**Comment by drsteve** [comment]
That ctypesgen is basically unmaintained right now. https://github.com/olsonse/ctypesgen is maintained and much improved. Give that one a shot...

**Comment by jtniehof** [comment]
That one seems to work, although it's structured slightly differently. I dropped it in to replace Python/ctypesgen and symlinked "run.py" to "ctypesgen.py" and that ran without error, and after install the few routines I was using worked.

So at some point I'll try cooking a PR that incorporates the latest ctypesgen cleanly (but won't cry if someone else gets there first.)

**Comment by drsteve** [comment]
Good to hear that. I'd been holding off on testing it a while back as the Python 3 compatibility was dribbling in. Hopefully the new version has fixed a bunch of the issues, as well as bringing Python 3 compatibility. Happy to take a PR when you have one!

**Comment by jtniehof** [comment]
Do we have a preference for handling ctypesgen? The options are 1) submodule, which is a ROYAL PAIN for everybody, including people who don't do any updates to ctypegen, 2) the existing copy-pasta, which rather loses history, and 3) subtree. The subtree approach can wind up pulling in the entire history of the other repo (ctypesgen in this case), or we can squash commits when we pull...it looks like we might not be able to avoid having a single merge commit at every pull from ctypesgen, though. So it'll look like:
```
*|  lgm code
 |* big honking ctypesgen commit
\/ merge
*|  lgm code
*|  lgm code
*|  lgm code
 |* big honking ctypesgen commit
\/ merge
```

instead of:
```
*|  lgm code
 |* ctypesgen commit
 |* ctypesgen commit
 |* ctypesgen commit
\/ merge
*|  lgm code
*|  lgm code
 |* ctypesgen commit
 |* ctypesgen commit
*|  lgm code
 |* ctypesgen commit
\/ merge
```

I'm looking into whether I can make the merge go away, so we'd just have a big rebased commit, but I fear that might just ruin the whole point of doing a subtree instead of just a copypasta.

**Comment by drsteve** [comment]
I feel a lot better about merge commits for updates to ctypesgen than I do about having them rebase-merged into our tree. The revision history in our repo should be a record of what we changed and when, not what ctypesgen changed and when. 

I guess PR #15 does a manual subtree (which is more-or-less copy-pasta, right?) so this way whenever we update we have a single jumbo commit? That's clean enough. Hopefully we won't need to update that often. I'll take a closer look over the PR now.

**Comment by jtniehof** [comment]
It is pretty similar to copypasta, but hopefully a little less error-prone. And should be single jumbo commit with no merge.

**Comment by drsteve** [comment]
Okay, I made the mistake of going back through multiple git revisions to look at where test results changed and now I'm back at HEAD and the library loader isn't finding LanlGeoMag.so.0, even though I can find it and it's in a standard location... I assume that this is working for you? Any suggestions on where to look?

**Comment by drsteve** [comment]
Just to clarify: this actually only happens with the new ctypesgen changes...

```
In [1]: import lgmpy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-842b5e2cf092> in <module>()
----> 1 import lgmpy

/usr/local/lib/python2.7/dist-packages/lgmpy/__init__.py in <module>()
     14 
     15 # Expose definitions from modules in this package.
---> 16 from lgmpy.Closed_Field import Closed_Field
     17 from Lgm_OP77 import OP77
     18 from Lgm_T89 import T89

/usr/local/lib/python2.7/dist-packages/lgmpy/Closed_Field.py in <module>()
     14 import math, numpy
     15 
---> 16 from Lgm_Wrap import Lgm_Trace, LGM_OPEN_IMF, LGM_CLOSED, LGM_OPEN_N_LOBE, LGM_BAD_TRACE
     17 from Lgm_Wrap import LGM_OPEN_S_LOBE, LGM_INSIDE_EARTH, LGM_TARGET_HEIGHT_UNREACHABLE
     18 from Lgm_Wrap import Lgm_Set_Lgm_B_OP77, Lgm_Set_Coord_Transforms, Lgm_Set_Lgm_B_T89

/usr/local/lib/python2.7/dist-packages/lgmpy/Lgm_Wrap.py in <module>()
    600 # Begin libraries
    601 _libs["hdf5"] = load_library("hdf5")
--> 602 _libs["LanlGeoMag"] = load_library("LanlGeoMag")
    603 
    604 # 2 libraries

/usr/local/lib/python2.7/dist-packages/lgmpy/Lgm_Wrap.py in load_library(self, libname)
    350                 return self.load(path)
    351 
--> 352         raise ImportError("%s not found." % libname)
    353 
    354     def load(self,path):

ImportError: LanlGeoMag not found.
```

**Comment by jtniehof** [comment]
It does work for me, but everytime I check out a new commit I make a point of make distclean; autoreconf -i -f; ./configure; make; make install

**Comment by drsteve** [comment]
The only thing I was doing differently was a simple `make clean` instead of `make distclean`.
I get the same error from the library loader regardless of whether I install as root (with `./configure`) or install locally using `./configure--prefix=/home/username/location/`

This is on Kubuntu 16.04.

**Comment by jtniehof** [comment]
It's been working for me on Xubuntu 16.04, so I doubt that's it. Can you give me a login on your machine and I'll poke? My configure is to /home/username/.local

**Comment by jtniehof** [comment]
I checked with an install into a non-standard location and indeed it does fail. There's some sed magic that probably needs to be updated for the new ctypesgen. I'll fix and open another PR.

**Comment by drsteve** [comment]
Thanks! I'll actually test the next one by pulling and building locally...
