### ISSUE TITLE
Lstar routine uses incorrect value for Bm

### ISSUE THREAD

**Issue by drsteve** [drsteve/LANLGeoMag#19]
On investigation of #16 I noticed that the magnetic field values being reported by `Lstar` were incorrect. The calculation appears to assume that the pitch angle being provided is the *equatorial* pitch angle, which is contrary to user expectation.

The calculation of Bm (line 634 of ComputeLstar.c) should be `LstarInfo->mInfo->Bm = LstarInfo->mInfo->Blocal/sa2;` and it should be checked that `Blocal` is being set correctly in the mInfo structure.

**Comment by jtniehof** [comment]
That would explain why the Python code was doing the conversion to equatorial before calling, and possibly why the Python code's attempts to calculate McIlwain/Hilton L from the invariant passed out of the L* calc was wrong.

**Comment by drsteve** [comment]
Well, it used to not actually precalculate any of that stuff at all. So ComputeLstarVersusPA would precompute Bmirror, but Lstar would (without documentation) assume that you'd precalculated all that stuff. This is likely my fault in setting the pitch angle to equatorial incorrectly when I made Lstar actually calculate the things it needs (from information it has) rather than assuming the user knows what needs to be calculated and where it should be tucked into the various structures. But yes, that confusing history may well have played into the Python code doing unnecessary things.

Anyway, it'll be fixed in a minute.
